### ISSUE TITLE
nodejs_14 has been removed as it is EOL

### ISSUE THREAD

**Issue by jordan-bravo** [jeff-hykin/nix_version_search_cli#4]
Is it possible to use nodejs_14 even though it is End Of Life?

![Screenshot from 2023-12-12 21-25-21](https://github.com/jeff-hykin/nix_version_search_cli/assets/62706808/c3f07e61-bd06-4953-99b9-8efa1297b2f3)

**Comment by jeff-hykin** [comment]
yes! Now, can this tool find the correct commit? I'm not sure. But I can tell you the best wworkaround for this problem in general.


The tool grabs data from 4 sites.
Those sites explore nixpkgs and build up a database.


Their logic is probably  
- if there's two commits
- both have the same version of X (e.g. NodeJS)
- Then only save the newer commit in the database

Which is obviously problematic for us in this scenario because the newest commit is an error message.

I've talked to the creators of all 4 sites in the past, so I can ask them about this and see if something can be done to handle this in general. 


For you specifically, I would;
- try a different patch release of node using nvs
- (if that doesn't work for you) use [nix-bisect](https://github.com/timokau/nix-bisect) to find other commits for nodejs. Skip to the part of their readme that says "You're fairly confident the build worked a while ago"
- (if that is too unclear) clone nixpkgs, start nix repl (use `nvs --repl nodejs@14` to get copy-paste code), use builtin.unsafePath (<- I can't quite remember the name of the method) to find the file path of nodejs14 attribute. Clone the nixpkgs repo, checkout the commit mentioned by `nvs`. Then look then look at the commit history for that specific file. Somewhere in that history will be the working version (the commit before they add the warning message). Get the commit hash and use that in the nix-shell command
